TEMPLATE = app
CONFIG += console
CONFIG -= app_bundle
CONFIG -= qt

SOURCES += \
        lv_drivers/display/GC9A01.c \
        lv_drivers/display/ILI9341.c \
        lv_drivers/display/R61581.c \
        lv_drivers/display/SHARP_MIP.c \
        lv_drivers/display/SSD1963.c \
        lv_drivers/display/ST7565.c \
        lv_drivers/display/UC1610.c \
        lv_drivers/display/drm.c \
        lv_drivers/display/fbdev.c \
        lv_drivers/gtkdrv/gtkdrv.c \
        lv_drivers/indev/AD_touch.c \
        lv_drivers/indev/FT5406EE8.c \
        lv_drivers/indev/XPT2046.c \
        lv_drivers/indev/evdev.c \
        lv_drivers/indev/libinput.c \
        lv_drivers/indev/xkb.c \
        lv_drivers/sdl/sdl.c \
        lv_drivers/sdl/sdl_gpu.c \
        lv_drivers/wayland/wayland.c \
        lv_drivers/win32drv/win32drv.c \
        lv_drivers/win_drv.c \
        lv_fs_if/lv_fs_fatfs.c \
        lv_fs_if/lv_fs_if.c \
        lv_fs_if/lv_fs_pc.c \
        lv_fs_if/lv_fs_posix.c \
        lvgl/examples/anim/lv_example_anim_1.c \
        lvgl/examples/anim/lv_example_anim_2.c \
        lvgl/examples/assets/animimg001.c \
        lvgl/examples/assets/animimg002.c \
        lvgl/examples/assets/animimg003.c \
        lvgl/examples/assets/img_caret_down.c \
        lvgl/examples/assets/img_cogwheel_alpha16.c \
        lvgl/examples/assets/img_cogwheel_argb.c \
        lvgl/examples/assets/img_cogwheel_chroma_keyed.c \
        lvgl/examples/assets/img_cogwheel_indexed16.c \
        lvgl/examples/assets/img_cogwheel_rgb.c \
        lvgl/examples/assets/img_hand.c \
        lvgl/examples/assets/img_skew_strip.c \
        lvgl/examples/assets/img_star.c \
        lvgl/examples/assets/imgbtn_left.c \
        lvgl/examples/assets/imgbtn_mid.c \
        lvgl/examples/assets/imgbtn_right.c \
        lvgl/examples/event/lv_example_event_1.c \
        lvgl/examples/event/lv_example_event_2.c \
        lvgl/examples/event/lv_example_event_3.c \
        lvgl/examples/get_started/lv_example_get_started_1.c \
        lvgl/examples/get_started/lv_example_get_started_2.c \
        lvgl/examples/get_started/lv_example_get_started_3.c \
        lvgl/examples/layouts/flex/lv_example_flex_1.c \
        lvgl/examples/layouts/flex/lv_example_flex_2.c \
        lvgl/examples/layouts/flex/lv_example_flex_3.c \
        lvgl/examples/layouts/flex/lv_example_flex_4.c \
        lvgl/examples/layouts/flex/lv_example_flex_5.c \
        lvgl/examples/layouts/flex/lv_example_flex_6.c \
        lvgl/examples/layouts/grid/lv_example_grid_1.c \
        lvgl/examples/layouts/grid/lv_example_grid_2.c \
        lvgl/examples/layouts/grid/lv_example_grid_3.c \
        lvgl/examples/layouts/grid/lv_example_grid_4.c \
        lvgl/examples/layouts/grid/lv_example_grid_5.c \
        lvgl/examples/layouts/grid/lv_example_grid_6.c \
        lvgl/examples/porting/lv_port_disp_template.c \
        lvgl/examples/porting/lv_port_fs_template.c \
        lvgl/examples/porting/lv_port_indev_template.c \
        lvgl/examples/scroll/lv_example_scroll_1.c \
        lvgl/examples/scroll/lv_example_scroll_2.c \
        lvgl/examples/scroll/lv_example_scroll_3.c \
        lvgl/examples/scroll/lv_example_scroll_4.c \
        lvgl/examples/scroll/lv_example_scroll_5.c \
        lvgl/examples/scroll/lv_example_scroll_6.c \
        lvgl/examples/styles/lv_example_style_1.c \
        lvgl/examples/styles/lv_example_style_10.c \
        lvgl/examples/styles/lv_example_style_11.c \
        lvgl/examples/styles/lv_example_style_12.c \
        lvgl/examples/styles/lv_example_style_13.c \
        lvgl/examples/styles/lv_example_style_14.c \
        lvgl/examples/styles/lv_example_style_2.c \
        lvgl/examples/styles/lv_example_style_3.c \
        lvgl/examples/styles/lv_example_style_4.c \
        lvgl/examples/styles/lv_example_style_5.c \
        lvgl/examples/styles/lv_example_style_6.c \
        lvgl/examples/styles/lv_example_style_7.c \
        lvgl/examples/styles/lv_example_style_8.c \
        lvgl/examples/styles/lv_example_style_9.c \
        lvgl/examples/widgets/animimg/lv_example_animimg_1.c \
        lvgl/examples/widgets/arc/lv_example_arc_1.c \
        lvgl/examples/widgets/arc/lv_example_arc_2.c \
        lvgl/examples/widgets/bar/lv_example_bar_1.c \
        lvgl/examples/widgets/bar/lv_example_bar_2.c \
        lvgl/examples/widgets/bar/lv_example_bar_3.c \
        lvgl/examples/widgets/bar/lv_example_bar_4.c \
        lvgl/examples/widgets/bar/lv_example_bar_5.c \
        lvgl/examples/widgets/bar/lv_example_bar_6.c \
        lvgl/examples/widgets/btn/lv_example_btn_1.c \
        lvgl/examples/widgets/btn/lv_example_btn_2.c \
        lvgl/examples/widgets/btn/lv_example_btn_3.c \
        lvgl/examples/widgets/btnmatrix/lv_example_btnmatrix_1.c \
        lvgl/examples/widgets/btnmatrix/lv_example_btnmatrix_2.c \
        lvgl/examples/widgets/btnmatrix/lv_example_btnmatrix_3.c \
        lvgl/examples/widgets/calendar/lv_example_calendar_1.c \
        lvgl/examples/widgets/canvas/lv_example_canvas_1.c \
        lvgl/examples/widgets/canvas/lv_example_canvas_2.c \
        lvgl/examples/widgets/chart/lv_example_chart_1.c \
        lvgl/examples/widgets/chart/lv_example_chart_2.c \
        lvgl/examples/widgets/chart/lv_example_chart_3.c \
        lvgl/examples/widgets/chart/lv_example_chart_4.c \
        lvgl/examples/widgets/chart/lv_example_chart_5.c \
        lvgl/examples/widgets/chart/lv_example_chart_6.c \
        lvgl/examples/widgets/chart/lv_example_chart_7.c \
        lvgl/examples/widgets/checkbox/lv_example_checkbox_1.c \
        lvgl/examples/widgets/colorwheel/lv_example_colorwheel_1.c \
        lvgl/examples/widgets/dropdown/lv_example_dropdown_1.c \
        lvgl/examples/widgets/dropdown/lv_example_dropdown_2.c \
        lvgl/examples/widgets/dropdown/lv_example_dropdown_3.c \
        lvgl/examples/widgets/img/lv_example_img_1.c \
        lvgl/examples/widgets/img/lv_example_img_2.c \
        lvgl/examples/widgets/img/lv_example_img_3.c \
        lvgl/examples/widgets/img/lv_example_img_4.c \
        lvgl/examples/widgets/imgbtn/lv_example_imgbtn_1.c \
        lvgl/examples/widgets/keyboard/lv_example_keyboard_1.c \
        lvgl/examples/widgets/label/lv_example_label_1.c \
        lvgl/examples/widgets/label/lv_example_label_2.c \
        lvgl/examples/widgets/label/lv_example_label_3.c \
        lvgl/examples/widgets/led/lv_example_led_1.c \
        lvgl/examples/widgets/line/lv_example_line_1.c \
        lvgl/examples/widgets/list/lv_example_list_1.c \
        lvgl/examples/widgets/meter/lv_example_meter_1.c \
        lvgl/examples/widgets/meter/lv_example_meter_2.c \
        lvgl/examples/widgets/meter/lv_example_meter_3.c \
        lvgl/examples/widgets/meter/lv_example_meter_4.c \
        lvgl/examples/widgets/msgbox/lv_example_msgbox_1.c \
        lvgl/examples/widgets/obj/lv_example_obj_1.c \
        lvgl/examples/widgets/obj/lv_example_obj_2.c \
        lvgl/examples/widgets/roller/lv_example_roller_1.c \
        lvgl/examples/widgets/roller/lv_example_roller_2.c \
        lvgl/examples/widgets/roller/lv_example_roller_3.c \
        lvgl/examples/widgets/slider/lv_example_slider_1.c \
        lvgl/examples/widgets/slider/lv_example_slider_2.c \
        lvgl/examples/widgets/slider/lv_example_slider_3.c \
        lvgl/examples/widgets/span/lv_example_span_1.c \
        lvgl/examples/widgets/spinbox/lv_example_spinbox_1.c \
        lvgl/examples/widgets/spinner/lv_example_spinner_1.c \
        lvgl/examples/widgets/switch/lv_example_switch_1.c \
        lvgl/examples/widgets/table/lv_example_table_1.c \
        lvgl/examples/widgets/table/lv_example_table_2.c \
        lvgl/examples/widgets/tabview/lv_example_tabview_1.c \
        lvgl/examples/widgets/tabview/lv_example_tabview_2.c \
        lvgl/examples/widgets/textarea/lv_example_textarea_1.c \
        lvgl/examples/widgets/textarea/lv_example_textarea_2.c \
        lvgl/examples/widgets/textarea/lv_example_textarea_3.c \
        lvgl/examples/widgets/tileview/lv_example_tileview_1.c \
        lvgl/examples/widgets/win/lv_example_win_1.c \
        lvgl/src/core/lv_disp.c \
        lvgl/src/core/lv_event.c \
        lvgl/src/core/lv_group.c \
        lvgl/src/core/lv_indev.c \
        lvgl/src/core/lv_indev_scroll.c \
        lvgl/src/core/lv_obj.c \
        lvgl/src/core/lv_obj_class.c \
        lvgl/src/core/lv_obj_draw.c \
        lvgl/src/core/lv_obj_pos.c \
        lvgl/src/core/lv_obj_scroll.c \
        lvgl/src/core/lv_obj_style.c \
        lvgl/src/core/lv_obj_style_gen.c \
        lvgl/src/core/lv_obj_tree.c \
        lvgl/src/core/lv_refr.c \
        lvgl/src/core/lv_theme.c \
        lvgl/src/draw/lv_draw_arc.c \
        lvgl/src/draw/lv_draw_blend.c \
        lvgl/src/draw/lv_draw_img.c \
        lvgl/src/draw/lv_draw_label.c \
        lvgl/src/draw/lv_draw_line.c \
        lvgl/src/draw/lv_draw_mask.c \
        lvgl/src/draw/lv_draw_rect.c \
        lvgl/src/draw/lv_draw_triangle.c \
        lvgl/src/draw/lv_img_buf.c \
        lvgl/src/draw/lv_img_cache.c \
        lvgl/src/draw/lv_img_decoder.c \
        lvgl/src/extra/layouts/flex/lv_flex.c \
        lvgl/src/extra/layouts/grid/lv_grid.c \
        lvgl/src/extra/lv_extra.c \
        lvgl/src/extra/themes/basic/lv_theme_basic.c \
        lvgl/src/extra/themes/default/lv_theme_default.c \
        lvgl/src/extra/themes/mono/lv_theme_mono.c \
        lvgl/src/extra/widgets/animimg/lv_animimg.c \
        lvgl/src/extra/widgets/calendar/lv_calendar.c \
        lvgl/src/extra/widgets/calendar/lv_calendar_header_arrow.c \
        lvgl/src/extra/widgets/calendar/lv_calendar_header_dropdown.c \
        lvgl/src/extra/widgets/chart/lv_chart.c \
        lvgl/src/extra/widgets/colorwheel/lv_colorwheel.c \
        lvgl/src/extra/widgets/imgbtn/lv_imgbtn.c \
        lvgl/src/extra/widgets/keyboard/lv_keyboard.c \
        lvgl/src/extra/widgets/led/lv_led.c \
        lvgl/src/extra/widgets/list/lv_list.c \
        lvgl/src/extra/widgets/meter/lv_meter.c \
        lvgl/src/extra/widgets/msgbox/lv_msgbox.c \
        lvgl/src/extra/widgets/span/lv_span.c \
        lvgl/src/extra/widgets/spinbox/lv_spinbox.c \
        lvgl/src/extra/widgets/spinner/lv_spinner.c \
        lvgl/src/extra/widgets/tabview/lv_tabview.c \
        lvgl/src/extra/widgets/tileview/lv_tileview.c \
        lvgl/src/extra/widgets/win/lv_win.c \
        lvgl/src/font/lv_font.c \
        lvgl/src/font/lv_font_dejavu_16_persian_hebrew.c \
        lvgl/src/font/lv_font_fmt_txt.c \
        lvgl/src/font/lv_font_loader.c \
        lvgl/src/font/lv_font_montserrat_10.c \
        lvgl/src/font/lv_font_montserrat_12.c \
        lvgl/src/font/lv_font_montserrat_12_subpx.c \
        lvgl/src/font/lv_font_montserrat_14.c \
        lvgl/src/font/lv_font_montserrat_16.c \
        lvgl/src/font/lv_font_montserrat_18.c \
        lvgl/src/font/lv_font_montserrat_20.c \
        lvgl/src/font/lv_font_montserrat_22.c \
        lvgl/src/font/lv_font_montserrat_24.c \
        lvgl/src/font/lv_font_montserrat_26.c \
        lvgl/src/font/lv_font_montserrat_28.c \
        lvgl/src/font/lv_font_montserrat_28_compressed.c \
        lvgl/src/font/lv_font_montserrat_30.c \
        lvgl/src/font/lv_font_montserrat_32.c \
        lvgl/src/font/lv_font_montserrat_34.c \
        lvgl/src/font/lv_font_montserrat_36.c \
        lvgl/src/font/lv_font_montserrat_38.c \
        lvgl/src/font/lv_font_montserrat_40.c \
        lvgl/src/font/lv_font_montserrat_42.c \
        lvgl/src/font/lv_font_montserrat_44.c \
        lvgl/src/font/lv_font_montserrat_46.c \
        lvgl/src/font/lv_font_montserrat_48.c \
        lvgl/src/font/lv_font_montserrat_8.c \
        lvgl/src/font/lv_font_simsun_16_cjk.c \
        lvgl/src/font/lv_font_unscii_16.c \
        lvgl/src/font/lv_font_unscii_8.c \
        lvgl/src/gpu/lv_gpu_nxp_pxp.c \
        lvgl/src/gpu/lv_gpu_nxp_pxp_osa.c \
        lvgl/src/gpu/lv_gpu_nxp_vglite.c \
        lvgl/src/gpu/lv_gpu_stm32_dma2d.c \
        lvgl/src/hal/lv_hal_disp.c \
        lvgl/src/hal/lv_hal_indev.c \
        lvgl/src/hal/lv_hal_tick.c \
        lvgl/src/misc/lv_anim.c \
        lvgl/src/misc/lv_area.c \
        lvgl/src/misc/lv_async.c \
        lvgl/src/misc/lv_bidi.c \
        lvgl/src/misc/lv_color.c \
        lvgl/src/misc/lv_fs.c \
        lvgl/src/misc/lv_gc.c \
        lvgl/src/misc/lv_ll.c \
        lvgl/src/misc/lv_log.c \
        lvgl/src/misc/lv_math.c \
        lvgl/src/misc/lv_mem.c \
        lvgl/src/misc/lv_printf.c \
        lvgl/src/misc/lv_style.c \
        lvgl/src/misc/lv_style_gen.c \
        lvgl/src/misc/lv_templ.c \
        lvgl/src/misc/lv_timer.c \
        lvgl/src/misc/lv_tlsf.c \
        lvgl/src/misc/lv_txt.c \
        lvgl/src/misc/lv_txt_ap.c \
        lvgl/src/misc/lv_utils.c \
        lvgl/src/widgets/lv_arc.c \
        lvgl/src/widgets/lv_bar.c \
        lvgl/src/widgets/lv_btn.c \
        lvgl/src/widgets/lv_btnmatrix.c \
        lvgl/src/widgets/lv_canvas.c \
        lvgl/src/widgets/lv_checkbox.c \
        lvgl/src/widgets/lv_dropdown.c \
        lvgl/src/widgets/lv_img.c \
        lvgl/src/widgets/lv_label.c \
        lvgl/src/widgets/lv_line.c \
        lvgl/src/widgets/lv_objx_templ.c \
        lvgl/src/widgets/lv_roller.c \
        lvgl/src/widgets/lv_slider.c \
        lvgl/src/widgets/lv_switch.c \
        lvgl/src/widgets/lv_table.c \
        lvgl/src/widgets/lv_textarea.c \
        lvgl/tests/lv_test_assert.c \
        lvgl/tests/lv_test_core/lv_test_core.c \
        lvgl/tests/lv_test_core/lv_test_font_loader.c \
        lvgl/tests/lv_test_core/lv_test_obj.c \
        lvgl/tests/lv_test_core/lv_test_style.c \
        lvgl/tests/lv_test_fonts/font_1.c \
        lvgl/tests/lv_test_fonts/font_2.c \
        lvgl/tests/lv_test_fonts/font_3.c \
        lvgl/tests/lv_test_main.c \
        lvgl/tests/lv_test_widgets/lv_test_label.c \
        main.c \
        mouse_cursor_icon.c

HEADERS += \
    lv_conf.h \
    lv_drivers/display/GC9A01.h \
    lv_drivers/display/ILI9341.h \
    lv_drivers/display/R61581.h \
    lv_drivers/display/SHARP_MIP.h \
    lv_drivers/display/SSD1963.h \
    lv_drivers/display/ST7565.h \
    lv_drivers/display/UC1610.h \
    lv_drivers/display/drm.h \
    lv_drivers/display/fbdev.h \
    lv_drivers/display/monitor.h \
    lv_drivers/gtkdrv/gtkdrv.h \
    lv_drivers/indev/AD_touch.h \
    lv_drivers/indev/FT5406EE8.h \
    lv_drivers/indev/XPT2046.h \
    lv_drivers/indev/evdev.h \
    lv_drivers/indev/keyboard.h \
    lv_drivers/indev/libinput_drv.h \
    lv_drivers/indev/mouse.h \
    lv_drivers/indev/mousewheel.h \
    lv_drivers/indev/xkb.h \
    lv_drivers/lv_drv_conf_template.h \
    lv_drivers/sdl/sdl.h \
    lv_drivers/sdl/sdl_gpu.h \
    lv_drivers/wayland/wayland.h \
    lv_drivers/win32drv/win32drv.h \
    lv_drivers/win_drv.h \
    lv_drv_conf.h \
    lv_fs_if/lv_fs_if.h \
    lvgl/examples/anim/lv_example_anim.h \
    lvgl/examples/event/lv_example_event.h \
    lvgl/examples/get_started/lv_example_get_started.h \
    lvgl/examples/layouts/flex/lv_example_flex.h \
    lvgl/examples/layouts/grid/lv_example_grid.h \
    lvgl/examples/layouts/lv_example_layout.h \
    lvgl/examples/lv_examples.h \
    lvgl/examples/porting/lv_port_disp_template.h \
    lvgl/examples/porting/lv_port_fs_template.h \
    lvgl/examples/porting/lv_port_indev_template.h \
    lvgl/examples/scroll/lv_example_scroll.h \
    lvgl/examples/styles/lv_example_style.h \
    lvgl/examples/widgets/lv_example_widgets.h \
    lvgl/lv_conf_template.h \
    lvgl/lvgl.h \
    lvgl/src/core/lv_disp.h \
    lvgl/src/core/lv_event.h \
    lvgl/src/core/lv_group.h \
    lvgl/src/core/lv_indev.h \
    lvgl/src/core/lv_indev_scroll.h \
    lvgl/src/core/lv_obj.h \
    lvgl/src/core/lv_obj_class.h \
    lvgl/src/core/lv_obj_draw.h \
    lvgl/src/core/lv_obj_pos.h \
    lvgl/src/core/lv_obj_scroll.h \
    lvgl/src/core/lv_obj_style.h \
    lvgl/src/core/lv_obj_style_gen.h \
    lvgl/src/core/lv_obj_tree.h \
    lvgl/src/core/lv_refr.h \
    lvgl/src/core/lv_theme.h \
    lvgl/src/draw/lv_draw.h \
    lvgl/src/draw/lv_draw_arc.h \
    lvgl/src/draw/lv_draw_blend.h \
    lvgl/src/draw/lv_draw_img.h \
    lvgl/src/draw/lv_draw_label.h \
    lvgl/src/draw/lv_draw_line.h \
    lvgl/src/draw/lv_draw_mask.h \
    lvgl/src/draw/lv_draw_rect.h \
    lvgl/src/draw/lv_draw_triangle.h \
    lvgl/src/draw/lv_img_buf.h \
    lvgl/src/draw/lv_img_cache.h \
    lvgl/src/draw/lv_img_decoder.h \
    lvgl/src/extra/layouts/flex/lv_flex.h \
    lvgl/src/extra/layouts/grid/lv_grid.h \
    lvgl/src/extra/layouts/lv_layouts.h \
    lvgl/src/extra/lv_extra.h \
    lvgl/src/extra/themes/basic/lv_theme_basic.h \
    lvgl/src/extra/themes/default/lv_theme_default.h \
    lvgl/src/extra/themes/lv_themes.h \
    lvgl/src/extra/themes/mono/lv_theme_mono.h \
    lvgl/src/extra/widgets/animimg/lv_animimg.h \
    lvgl/src/extra/widgets/calendar/lv_calendar.h \
    lvgl/src/extra/widgets/calendar/lv_calendar_header_arrow.h \
    lvgl/src/extra/widgets/calendar/lv_calendar_header_dropdown.h \
    lvgl/src/extra/widgets/chart/lv_chart.h \
    lvgl/src/extra/widgets/colorwheel/lv_colorwheel.h \
    lvgl/src/extra/widgets/imgbtn/lv_imgbtn.h \
    lvgl/src/extra/widgets/keyboard/lv_keyboard.h \
    lvgl/src/extra/widgets/led/lv_led.h \
    lvgl/src/extra/widgets/list/lv_list.h \
    lvgl/src/extra/widgets/lv_widgets.h \
    lvgl/src/extra/widgets/meter/lv_meter.h \
    lvgl/src/extra/widgets/msgbox/lv_msgbox.h \
    lvgl/src/extra/widgets/span/lv_span.h \
    lvgl/src/extra/widgets/spinbox/lv_spinbox.h \
    lvgl/src/extra/widgets/spinner/lv_spinner.h \
    lvgl/src/extra/widgets/tabview/lv_tabview.h \
    lvgl/src/extra/widgets/tileview/lv_tileview.h \
    lvgl/src/extra/widgets/win/lv_win.h \
    lvgl/src/font/lv_font.h \
    lvgl/src/font/lv_font_fmt_txt.h \
    lvgl/src/font/lv_font_loader.h \
    lvgl/src/font/lv_symbol_def.h \
    lvgl/src/gpu/lv_gpu_nxp_pxp.h \
    lvgl/src/gpu/lv_gpu_nxp_pxp_osa.h \
    lvgl/src/gpu/lv_gpu_nxp_vglite.h \
    lvgl/src/gpu/lv_gpu_stm32_dma2d.h \
    lvgl/src/hal/lv_hal.h \
    lvgl/src/hal/lv_hal_disp.h \
    lvgl/src/hal/lv_hal_indev.h \
    lvgl/src/hal/lv_hal_tick.h \
    lvgl/src/lv_api_map.h \
    lvgl/src/lv_conf_internal.h \
    lvgl/src/lv_conf_kconfig.h \
    lvgl/src/lvgl.h \
    lvgl/src/misc/lv_anim.h \
    lvgl/src/misc/lv_area.h \
    lvgl/src/misc/lv_assert.h \
    lvgl/src/misc/lv_async.h \
    lvgl/src/misc/lv_bidi.h \
    lvgl/src/misc/lv_color.h \
    lvgl/src/misc/lv_fs.h \
    lvgl/src/misc/lv_gc.h \
    lvgl/src/misc/lv_ll.h \
    lvgl/src/misc/lv_log.h \
    lvgl/src/misc/lv_math.h \
    lvgl/src/misc/lv_mem.h \
    lvgl/src/misc/lv_printf.h \
    lvgl/src/misc/lv_style.h \
    lvgl/src/misc/lv_style_gen.h \
    lvgl/src/misc/lv_templ.h \
    lvgl/src/misc/lv_timer.h \
    lvgl/src/misc/lv_tlsf.h \
    lvgl/src/misc/lv_txt.h \
    lvgl/src/misc/lv_txt_ap.h \
    lvgl/src/misc/lv_types.h \
    lvgl/src/misc/lv_utils.h \
    lvgl/src/widgets/lv_arc.h \
    lvgl/src/widgets/lv_bar.h \
    lvgl/src/widgets/lv_btn.h \
    lvgl/src/widgets/lv_btnmatrix.h \
    lvgl/src/widgets/lv_canvas.h \
    lvgl/src/widgets/lv_checkbox.h \
    lvgl/src/widgets/lv_dropdown.h \
    lvgl/src/widgets/lv_img.h \
    lvgl/src/widgets/lv_label.h \
    lvgl/src/widgets/lv_line.h \
    lvgl/src/widgets/lv_objx_templ.h \
    lvgl/src/widgets/lv_roller.h \
    lvgl/src/widgets/lv_slider.h \
    lvgl/src/widgets/lv_switch.h \
    lvgl/src/widgets/lv_table.h \
    lvgl/src/widgets/lv_textarea.h \
    lvgl/tests/lv_test_assert.h \
    lvgl/tests/lv_test_conf.h \
    lvgl/tests/lv_test_core/lv_test_core.h \
    lvgl/tests/lv_test_core/lv_test_font_loader.h \
    lvgl/tests/lv_test_core/lv_test_obj.h \
    lvgl/tests/lv_test_core/lv_test_style.h \
    lvgl/tests/lv_test_widgets/lv_test_label.h

LIBS += -L/usr/local/lib -lSDL2 -ldl -lpthread
INCLUDES += /usr/local/include
#LIBS += -L$$PWD/lib/ -lmingw32 -lSDL2main -lSDL2
